// flow-typed signature: f58f1f3be04e5cb5d18c06ea0eb68c4b
// flow-typed version: <<STUB>>/@habx/lib-mq-aws_v^4.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@habx/lib-mq-aws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@habx/lib-mq-aws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@habx/lib-mq-aws/dist/index' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/AWSEnvironment' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/AWSManager' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/Cleaner' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSNS' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSNS.test' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQS' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQS.test-disabled' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS.test-disabled' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSubscription' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/ensureSubscription.test-disabled' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys.test' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/wrapError' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/lib/wrapError.test' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/QueueManager' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/QueueManager.test' {
  declare module.exports: any;
}

declare module '@habx/lib-mq-aws/dist/src/TopicManager' {
  declare module.exports: any;
}

// Filename aliases
declare module '@habx/lib-mq-aws/dist/index.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/index'>;
}
declare module '@habx/lib-mq-aws/dist/src/AWSEnvironment.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/AWSEnvironment'>;
}
declare module '@habx/lib-mq-aws/dist/src/AWSManager.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/AWSManager'>;
}
declare module '@habx/lib-mq-aws/dist/src/Cleaner.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/Cleaner'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSNS.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSNS'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSNS.test.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSNS.test'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQS.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSQS'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQS.test-disabled.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSQS.test-disabled'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS.test-disabled.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSQSAllowsSNS.test-disabled'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSubscription.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSubscription'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/ensureSubscription.test-disabled.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/ensureSubscription.test-disabled'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys.test.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/isEqualSharedKeys.test'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/wrapError.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/wrapError'>;
}
declare module '@habx/lib-mq-aws/dist/src/lib/wrapError.test.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/lib/wrapError.test'>;
}
declare module '@habx/lib-mq-aws/dist/src/QueueManager.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/QueueManager'>;
}
declare module '@habx/lib-mq-aws/dist/src/QueueManager.test.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/QueueManager.test'>;
}
declare module '@habx/lib-mq-aws/dist/src/TopicManager.js' {
  declare module.exports: $Exports<'@habx/lib-mq-aws/dist/src/TopicManager'>;
}
