// flow-typed signature: f8e3bd2fae5e927af4d9ba5d5cfc860b
// flow-typed version: <<STUB>>/aws-sqs-consumer_v^2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-sqs-consumer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-sqs-consumer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-sqs-consumer/src/Consumer' {
  declare module.exports: any;
}

declare module 'aws-sqs-consumer/src/ConsumerDefaults' {
  declare module.exports: any;
}

declare module 'aws-sqs-consumer/src/ConsumerManager' {
  declare module.exports: any;
}

declare module 'aws-sqs-consumer/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-sqs-consumer/src/Consumer.js' {
  declare module.exports: $Exports<'aws-sqs-consumer/src/Consumer'>;
}
declare module 'aws-sqs-consumer/src/ConsumerDefaults.js' {
  declare module.exports: $Exports<'aws-sqs-consumer/src/ConsumerDefaults'>;
}
declare module 'aws-sqs-consumer/src/ConsumerManager.js' {
  declare module.exports: $Exports<'aws-sqs-consumer/src/ConsumerManager'>;
}
declare module 'aws-sqs-consumer/src/index.js' {
  declare module.exports: $Exports<'aws-sqs-consumer/src/index'>;
}
