// flow-typed signature: 63b58693754cf4872cb0775f89f21ad5
// flow-typed version: <<STUB>>/json-formatter-js_v^2.2.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-formatter-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-formatter-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-formatter-js/demo/index' {
  declare module.exports: any;
}

declare module 'json-formatter-js/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'json-formatter-js/dist/demo/index' {
  declare module.exports: any;
}

declare module 'json-formatter-js/dist/json-formatter' {
  declare module.exports: any;
}

declare module 'json-formatter-js/server' {
  declare module.exports: any;
}

declare module 'json-formatter-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-formatter-js/demo/index.js' {
  declare module.exports: $Exports<'json-formatter-js/demo/index'>;
}
declare module 'json-formatter-js/demo/webpack.config.js' {
  declare module.exports: $Exports<'json-formatter-js/demo/webpack.config'>;
}
declare module 'json-formatter-js/dist/demo/index.js' {
  declare module.exports: $Exports<'json-formatter-js/dist/demo/index'>;
}
declare module 'json-formatter-js/dist/json-formatter.js' {
  declare module.exports: $Exports<'json-formatter-js/dist/json-formatter'>;
}
declare module 'json-formatter-js/server.js' {
  declare module.exports: $Exports<'json-formatter-js/server'>;
}
declare module 'json-formatter-js/webpack.config.js' {
  declare module.exports: $Exports<'json-formatter-js/webpack.config'>;
}
