// flow-typed signature: e55a665e038d696f273434bc75281f3a
// flow-typed version: <<STUB>>/jsoneditor_v^5.28.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsoneditor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsoneditor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsoneditor/dist/jsoneditor-minimalist' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor-minimalist.min' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor.min' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/App' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/App.test' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/index' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/App' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/App.test' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/index' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/JSONEditorDemo' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/requirejs_demo/scripts/main' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/requirejs_demo/scripts/require' {
  declare module.exports: any;
}

declare module 'jsoneditor/gulpfile' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ace/index' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ace/theme-jsoneditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/appendNodeFactory' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/assets/jsonlint/jsonlint' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/assets/selectr/selectr' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/autocomplete' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ContextMenu' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/createAbsoluteAnchor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/header' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/Highlighter' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/History' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/i18n' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/JSONEditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ModeSwitcher' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/Node' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/SearchBox' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showMoreNodeFactory' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showSortModal' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showTransformModal' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/textmode' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/treemode' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/TreePath' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/util' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/vanilla-picker/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsoneditor/dist/jsoneditor-minimalist.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor-minimalist'>;
}
declare module 'jsoneditor/dist/jsoneditor-minimalist.min.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor-minimalist.min'>;
}
declare module 'jsoneditor/dist/jsoneditor.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor'>;
}
declare module 'jsoneditor/dist/jsoneditor.min.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor.min'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/App.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/App'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/App.test.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/App.test'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/index.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/index'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact'>;
}
declare module 'jsoneditor/examples/react_demo/src/App.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/App'>;
}
declare module 'jsoneditor/examples/react_demo/src/App.test.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/App.test'>;
}
declare module 'jsoneditor/examples/react_demo/src/index.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/index'>;
}
declare module 'jsoneditor/examples/react_demo/src/JSONEditorDemo.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/JSONEditorDemo'>;
}
declare module 'jsoneditor/examples/requirejs_demo/scripts/main.js' {
  declare module.exports: $Exports<'jsoneditor/examples/requirejs_demo/scripts/main'>;
}
declare module 'jsoneditor/examples/requirejs_demo/scripts/require.js' {
  declare module.exports: $Exports<'jsoneditor/examples/requirejs_demo/scripts/require'>;
}
declare module 'jsoneditor/gulpfile.js' {
  declare module.exports: $Exports<'jsoneditor/gulpfile'>;
}
declare module 'jsoneditor/index' {
  declare module.exports: $Exports<'jsoneditor'>;
}
declare module 'jsoneditor/index.js' {
  declare module.exports: $Exports<'jsoneditor'>;
}
declare module 'jsoneditor/src/js/ace/index.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ace/index'>;
}
declare module 'jsoneditor/src/js/ace/theme-jsoneditor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ace/theme-jsoneditor'>;
}
declare module 'jsoneditor/src/js/appendNodeFactory.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/appendNodeFactory'>;
}
declare module 'jsoneditor/src/js/assets/jsonlint/jsonlint.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/assets/jsonlint/jsonlint'>;
}
declare module 'jsoneditor/src/js/assets/selectr/selectr.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/assets/selectr/selectr'>;
}
declare module 'jsoneditor/src/js/autocomplete.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/autocomplete'>;
}
declare module 'jsoneditor/src/js/ContextMenu.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ContextMenu'>;
}
declare module 'jsoneditor/src/js/createAbsoluteAnchor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/createAbsoluteAnchor'>;
}
declare module 'jsoneditor/src/js/header.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/header'>;
}
declare module 'jsoneditor/src/js/Highlighter.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/Highlighter'>;
}
declare module 'jsoneditor/src/js/History.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/History'>;
}
declare module 'jsoneditor/src/js/i18n.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/i18n'>;
}
declare module 'jsoneditor/src/js/JSONEditor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/JSONEditor'>;
}
declare module 'jsoneditor/src/js/ModeSwitcher.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ModeSwitcher'>;
}
declare module 'jsoneditor/src/js/Node.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/Node'>;
}
declare module 'jsoneditor/src/js/SearchBox.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/SearchBox'>;
}
declare module 'jsoneditor/src/js/showMoreNodeFactory.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showMoreNodeFactory'>;
}
declare module 'jsoneditor/src/js/showSortModal.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showSortModal'>;
}
declare module 'jsoneditor/src/js/showTransformModal.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showTransformModal'>;
}
declare module 'jsoneditor/src/js/textmode.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/textmode'>;
}
declare module 'jsoneditor/src/js/treemode.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/treemode'>;
}
declare module 'jsoneditor/src/js/TreePath.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/TreePath'>;
}
declare module 'jsoneditor/src/js/util.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/util'>;
}
declare module 'jsoneditor/src/js/vanilla-picker/index.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/vanilla-picker/index'>;
}
